server:
  port: 80
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order
#  1
#  activemq:
#    broker-url: tcp://localhost:61616
#  jms:
#    template:
#      default-destination: yihe
#    pub-sub-domain: true


#  2
#  rabbitmq:
#    host: localhost
#    port: 5672
#    发布订阅

# 3.rocketmq
#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: group_rocketmq
